spring:
  cloud:
    gateway:
      routes:
        - id: main_site
          uri: http://kourier-internal.knative-serving.svc.cluster.local:80
          predicates:
            - Host=gateway.jonasandersen-no.svc.cluster.local
          filters:
            - name: SetRequestHostHeader
              args:
                hostHeader: website.jonasandersen-no.svc.cluster.local

logging:
  level:
    org.springframework.cloud.gateway: TRACE
