jonas:
  gateway:
    routes:
      - patterns:
          - jonasandersen.no
          - test.jonasandersen.no
          - www.jonasandersen.no
        host-header: website.jonasandersen-no.svc.cluster.local
      - patterns:
          - login.jonasandersen.no
        host-header: login.jonasandersen-no.svc.cluster.local
      - patterns:
          - api.jonasandersen.no
        host-header: linode4j.jonasandersen-no.svc.cluster.local
        path-prefix: linode
management:
  endpoints:
    web:
      exposure:
        include: health